In [2]:
# Colab only: clone the repo and move into the project root
import os
import sys

# Check if running in Google Colab
if 'google.colab' in sys.modules:
    # Clone repository if it hasn't been cloned yet
    if not os.path.exists('/content/convolutional_vae_quishing'):
        !git clone https://github.com/AnhJoe/convolutional_vae_quishing.git

    # Change working directory to the project root
    os.chdir('/content/convolutional_vae_quishing')

In [3]:
#| output: false
# Local only: find the project root (the folder containing src/) and add it to the import path
# For local runs. Else if running Colab, skip this.

import sys
from pathlib import Path

# Set to root for src load
root = Path.cwd()
while root != root.parent and not (root / "src").exists():
    root = root.parent

if not (root / "src").exists():
    raise FileNotFoundError("Could not find 'src' folder above current working directory.")

sys.path.insert(0, str(root))
print("Project root:", root)

Project root: c:\Users\joetn\convolutional_vae_quishing

# Data processing

This notebook turns the cleaned manifest from `1_eda.ipynb` into one shared table, the **items table**, that every model notebook reads. Nothing here trains a model. It is run once, and the model notebooks (`3_image_vae.ipynb` and `4_url_vae.ipynb`) only read its output, so everyone trains, tunes and tests on identical data.

Run `1_eda.ipynb` first. It downloads the dataset into `data/raw` and saves `data/processed/manifest.csv.gz`, the list of every QR code with its cleaning decision. This notebook then does four things:

1. Counts which QR codes fit the 65 x 65 image canvas decided in `1_eda.ipynb` section 4.
2. Measures every QR image (size, quiet zone, dark fraction), which the image strata and the image floor need.
3. Assigns every code to train, validation or test, using the grouped rule decided in `1_eda.ipynb` section 6, and saves the items table.
4. Checks the splits.

Steps 1 and 2 read about a million image files, so they are slow (step 1 reads only the file header and is much faster than step 2). Both can be stopped and started again, and both skip work that is already saved. Everything is saved in `data/processed/`, which is git-ignored. The column-by-column description of the items table is at the top of `src/prepare_data.py`.

## 1. Load the cleaned manifest

The manifest has one row per URL from the source CSVs. Its `keep` column is false only for the 38 rows whose URL appears in both classes (`1_eda.ipynb` section 7), so the items table has 1,005,700 rows.

In [4]:
# Imports, paths and the time limit for the slow steps
import json

import numpy as np
import pandas as pd

from src import canvas_exclusion_count, prepare_data
from src.splits import SPLIT_NAMES

PROC_DIR = root / "data" / "processed"
RAW_DIR = root / "data" / "raw"

# None means no limit. In a time-limited session (for example Colab) set a number of seconds, such as 1200.
# The slow steps then stop politely after that time, and running the same cell again continues where it stopped.
MAX_SECONDS = None

if not (PROC_DIR / "manifest.csv.gz").exists():
    raise FileNotFoundError("data/processed/manifest.csv.gz not found. Run 1_eda.ipynb first.")
manifest = pd.read_csv(PROC_DIR / "manifest.csv.gz", usecols=["cls", "keep", "drop_reason"], keep_default_na=False)
print(f"{len(manifest):,} rows in the manifest, {int(manifest['keep'].sum()):,} kept")
manifest.groupby("cls")["keep"].agg(rows="size", kept="sum")

1,005,738 rows in the manifest, 1,005,700 kept

             rows    kept
cls
benign     429976  429957
malicious  575762  575743

## 2. Which codes fit the image canvas

The image VAE takes one fixed input size, a 65 x 65 grid of modules (a module is one black or white square of a QR code). A code whose grid, quiet zone included, is larger than that cannot be used without cropping, so it is excluded from the image model and counted. URL models use every row.

`canvas_exclusion_count.run` reads the size of every kept PNG (the 1,005,700 rows of the items table). It reads only the first bytes of each file (the header, not the pixels), and every image is drawn at 6 pixels per module, so the grid size is the image width divided by 6. It saves `image_grid_sizes.csv.gz` (one row per image) and `canvas_exclusion_summary.json` (counts per class).

In [5]:
# Measure the grid size of every kept image (header only). Skipped if the result is already saved
grid_file = PROC_DIR / "image_grid_sizes.csv.gz"
if grid_file.exists():
    print("already measured:", grid_file.name, "(delete the file to measure again)")
else:
    canvas_exclusion_count.run(root, max_seconds=MAX_SECONDS)

1,005,700 images, 0 already measured, 1,005,700 to do
  measured 5,000 of 1,005,700 in 1 s
  measured 10,000 of 1,005,700 in 2 s
  measured 15,000 of 1,005,700 in 3 s
  measured 20,000 of 1,005,700 in 4 s
  measured 25,000 of 1,005,700 in 5 s
  measured 30,000 of 1,005,700 in 6 s
  measured 35,000 of 1,005,700 in 7 s
  measured 40,000 of 1,005,700 in 8 s
  measured 45,000 of 1,005,700 in 9 s
  measured 50,000 of 1,005,700 in 10 s
  measured 55,000 of 1,005,700 in 12 s
  measured 60,000 of 1,005,700 in 13 s
  measured 65,000 of 1,005,700 in 13 s
  measured 70,000 of 1,005,700 in 14 s
  measured 75,000 of 1,005,700 in 16 s
  measured 80,000 of 1,005,700 in 16 s
  measured 85,000 of 1,005,700 in 18 s
  measured 90,000 of 1,005,700 in 18 s
  measured 95,000 of 1,005,700 in 20 s
  measured 100,000 of 1,005,700 in 20 s
  measured 105,000 of 1,005,700 in 21 s
  measured 110,000 of 1,005,700 in 22 s
  measured 115,000 of 1,005,700 in 23 s
  measured 120,000 of 1,005,700 in 25 s
  measured 125,000 of 1,005,700 in 26 s
  measured 130,000 of 1,005,700 in 26 s
  measured 135,000 of 1,005,700 in 27 s
  measured 140,000 of 1,005,700 in 28 s
  measured 145,000 of 1,005,700 in 30 s
  measured 150,000 of 1,005,700 in 31 s
  measured 155,000 of 1,005,700 in 31 s
  measured 160,000 of 1,005,700 in 32 s
  measured 165,000 of 1,005,700 in 33 s
  measured 170,000 of 1,005,700 in 35 s
  measured 175,000 of 1,005,700 in 36 s
  measured 180,000 of 1,005,700 in 37 s
  measured 185,000 of 1,005,700 in 37 s
  measured 190,000 of 1,005,700 in 38 s
  measured 195,000 of 1,005,700 in 39 s
  measured 200,000 of 1,005,700 in 41 s
  measured 205,000 of 1,005,700 in 41 s
  measured 210,000 of 1,005,700 in 42 s
  measured 215,000 of 1,005,700 in 43 s
  measured 220,000 of 1,005,700 in 44 s
  measured 225,000 of 1,005,700 in 46 s
  measured 230,000 of 1,005,700 in 47 s
  measured 235,000 of 1,005,700 in 48 s
  measured 240,000 of 1,005,700 in 49 s
  measured 245,000 of 1,005,700 in 50 s
  measured 250,000 of 1,005,700 in 51 s
  measured 255,000 of 1,005,700 in 52 s
  measured 260,000 of 1,005,700 in 53 s
  measured 265,000 of 1,005,700 in 54 s
  measured 270,000 of 1,005,700 in 55 s
  measured 275,000 of 1,005,700 in 56 s
  measured 280,000 of 1,005,700 in 57 s
  measured 285,000 of 1,005,700 in 58 s
  measured 290,000 of 1,005,700 in 59 s
  measured 295,000 of 1,005,700 in 60 s
  measured 300,000 of 1,005,700 in 61 s
  measured 305,000 of 1,005,700 in 62 s
  measured 310,000 of 1,005,700 in 63 s
  measured 315,000 of 1,005,700 in 64 s
  measured 320,000 of 1,005,700 in 65 s
  measured 325,000 of 1,005,700 in 67 s
  measured 330,000 of 1,005,700 in 68 s
  measured 335,000 of 1,005,700 in 69 s
  measured 340,000 of 1,005,700 in 70 s
  measured 345,000 of 1,005,700 in 71 s
  measured 350,000 of 1,005,700 in 72 s
  measured 355,000 of 1,005,700 in 73 s
  measured 360,000 of 1,005,700 in 74 s
  measured 365,000 of 1,005,700 in 75 s
  measured 370,000 of 1,005,700 in 76 s
  measured 375,000 of 1,005,700 in 77 s
  measured 380,000 of 1,005,700 in 78 s
  measured 385,000 of 1,005,700 in 79 s
  measured 390,000 of 1,005,700 in 80 s
  measured 395,000 of 1,005,700 in 81 s
  measured 400,000 of 1,005,700 in 82 s
  measured 405,000 of 1,005,700 in 83 s
  measured 410,000 of 1,005,700 in 85 s
  measured 415,000 of 1,005,700 in 86 s
  measured 420,000 of 1,005,700 in 87 s
  measured 425,000 of 1,005,700 in 88 s
  measured 430,000 of 1,005,700 in 89 s
  measured 435,000 of 1,005,700 in 90 s
  measured 440,000 of 1,005,700 in 91 s
  measured 445,000 of 1,005,700 in 92 s
  measured 450,000 of 1,005,700 in 93 s
  measured 455,000 of 1,005,700 in 94 s
  measured 460,000 of 1,005,700 in 95 s
  measured 465,000 of 1,005,700 in 96 s
  measured 470,000 of 1,005,700 in 97 s
  measured 475,000 of 1,005,700 in 98 s
  measured 480,000 of 1,005,700 in 100 s
  measured 485,000 of 1,005,700 in 101 s
  measured 490,000 of 1,005,700 in 102 s
  measured 495,000 of 1,005,700 in 103 s
  measured 500,000 of 1,005,700 in 104 s
  measured 505,000 of 1,005,700 in 105 s
  measured 510,000 of 1,005,700 in 106 s
  measured 515,000 of 1,005,700 in 107 s
  measured 520,000 of 1,005,700 in 108 s
  measured 525,000 of 1,005,700 in 109 s
  measured 530,000 of 1,005,700 in 110 s
  measured 535,000 of 1,005,700 in 111 s
  measured 540,000 of 1,005,700 in 112 s
  measured 545,000 of 1,005,700 in 113 s
  measured 550,000 of 1,005,700 in 114 s
  measured 555,000 of 1,005,700 in 115 s
  measured 560,000 of 1,005,700 in 116 s
  measured 565,000 of 1,005,700 in 117 s
  measured 570,000 of 1,005,700 in 119 s
  measured 575,000 of 1,005,700 in 120 s
  measured 580,000 of 1,005,700 in 121 s
  measured 585,000 of 1,005,700 in 122 s
  measured 590,000 of 1,005,700 in 123 s
  measured 595,000 of 1,005,700 in 124 s
  measured 600,000 of 1,005,700 in 125 s
  measured 605,000 of 1,005,700 in 126 s
  measured 610,000 of 1,005,700 in 128 s
  measured 615,000 of 1,005,700 in 129 s
  measured 620,000 of 1,005,700 in 130 s
  measured 625,000 of 1,005,700 in 131 s
  measured 630,000 of 1,005,700 in 132 s
  measured 635,000 of 1,005,700 in 133 s
  measured 640,000 of 1,005,700 in 135 s
  measured 645,000 of 1,005,700 in 136 s
  measured 650,000 of 1,005,700 in 137 s
  measured 655,000 of 1,005,700 in 138 s
  measured 660,000 of 1,005,700 in 139 s
  measured 665,000 of 1,005,700 in 140 s
  measured 670,000 of 1,005,700 in 141 s
  measured 675,000 of 1,005,700 in 142 s
  measured 680,000 of 1,005,700 in 143 s
  measured 685,000 of 1,005,700 in 144 s
  measured 690,000 of 1,005,700 in 145 s
  measured 695,000 of 1,005,700 in 147 s
  measured 700,000 of 1,005,700 in 148 s
  measured 705,000 of 1,005,700 in 149 s
  measured 710,000 of 1,005,700 in 150 s
  measured 715,000 of 1,005,700 in 151 s
  measured 720,000 of 1,005,700 in 152 s
  measured 725,000 of 1,005,700 in 153 s
  measured 730,000 of 1,005,700 in 154 s
  measured 735,000 of 1,005,700 in 155 s
  measured 740,000 of 1,005,700 in 156 s
  measured 745,000 of 1,005,700 in 157 s
  measured 750,000 of 1,005,700 in 158 s
  measured 755,000 of 1,005,700 in 159 s
  measured 760,000 of 1,005,700 in 161 s
  measured 765,000 of 1,005,700 in 162 s
  measured 770,000 of 1,005,700 in 163 s
  measured 775,000 of 1,005,700 in 164 s
  measured 780,000 of 1,005,700 in 165 s
  measured 785,000 of 1,005,700 in 166 s
  measured 790,000 of 1,005,700 in 167 s
  measured 795,000 of 1,005,700 in 168 s
  measured 800,000 of 1,005,700 in 169 s
  measured 805,000 of 1,005,700 in 170 s
  measured 810,000 of 1,005,700 in 171 s
  measured 815,000 of 1,005,700 in 172 s
  measured 820,000 of 1,005,700 in 173 s
  measured 825,000 of 1,005,700 in 175 s
  measured 830,000 of 1,005,700 in 176 s
  measured 835,000 of 1,005,700 in 177 s
  measured 840,000 of 1,005,700 in 178 s
  measured 845,000 of 1,005,700 in 179 s
  measured 850,000 of 1,005,700 in 180 s
  measured 855,000 of 1,005,700 in 181 s
  measured 860,000 of 1,005,700 in 183 s
  measured 865,000 of 1,005,700 in 184 s
  measured 870,000 of 1,005,700 in 185 s
  measured 875,000 of 1,005,700 in 187 s
  measured 880,000 of 1,005,700 in 188 s
  measured 885,000 of 1,005,700 in 189 s
  measured 890,000 of 1,005,700 in 190 s
  measured 895,000 of 1,005,700 in 192 s
  measured 900,000 of 1,005,700 in 193 s
  measured 905,000 of 1,005,700 in 194 s
  measured 910,000 of 1,005,700 in 195 s
  measured 915,000 of 1,005,700 in 196 s
  measured 920,000 of 1,005,700 in 198 s
  measured 925,000 of 1,005,700 in 199 s
  measured 930,000 of 1,005,700 in 200 s
  measured 935,000 of 1,005,700 in 201 s
  measured 940,000 of 1,005,700 in 202 s
  measured 945,000 of 1,005,700 in 203 s
  measured 950,000 of 1,005,700 in 205 s
  measured 955,000 of 1,005,700 in 206 s
  measured 960,000 of 1,005,700 in 207 s
  measured 965,000 of 1,005,700 in 208 s
  measured 970,000 of 1,005,700 in 209 s
  measured 975,000 of 1,005,700 in 210 s
  measured 980,000 of 1,005,700 in 211 s
  measured 985,000 of 1,005,700 in 212 s
  measured 990,000 of 1,005,700 in 213 s
  measured 995,000 of 1,005,700 in 214 s
  measured 1,000,000 of 1,005,700 in 215 s
  measured 1,005,000 of 1,005,700 in 217 s
  measured 1,005,700 of 1,005,700 in 217 s

canvas 65 x 65 modules, 6 px per module
benign: 429,957 images, 157 outside the canvas (0.036%), irregular or unreadable: none
malicious: 575,743 images, 4,506 outside the canvas (0.783%), irregular or unreadable: none
saved c:\Users\joetn\convolutional_vae_quishing\data\processed\image_grid_sizes.csv.gz and c:\Users\joetn\convolutional_vae_quishing\data\processed\canvas_exclusion_summary.json

In [6]:
# Codes outside the 65 x 65 canvas, per class, over all kept images
cs = json.loads((PROC_DIR / "canvas_exclusion_summary.json").read_text())
excluded = pd.DataFrame({
    cls: {"images": s["images"], "outside the canvas": s["outside_canvas"], "outside share": round(s["outside_canvas_share"], 4),
          "largest grid (modules)": s["largest_grid"], "unreadable or irregular files": sum(s["irregular_or_unreadable"].values())}
    for cls, s in cs["per_class"].items()})
display(excluded)

                                    benign    malicious
images                         429957.0000  575743.0000
outside the canvas                157.0000    4506.0000
outside share                       0.0004       0.0078
largest grid (modules)            125.0000     169.0000
unreadable or irregular files       0.0000       0.0000

**Reading.** The first table is the count of excluded codes over all kept images.

## 3. Measure every QR image

The image strata and the image floor need three properties of every code: its number of modules per side (which gives the QR version, with Micro QR codes below 21 modules as their own group), the width of its quiet zone, and the fraction of dark pixels. `prepare_data.run_images` measures them with the method used in `1_eda.ipynb` section 4, for every kept image, and saves `image_features.csv.gz`. This reads every PNG, so it is the slowest step. Run it again to continue after a stop.

In [7]:
# Measure modules, quiet zone and dark fraction of every kept image. Skipped if the result is already saved
features_file = PROC_DIR / prepare_data.IMAGE_FEATURES_FILE
if features_file.exists():
    print("already measured:", features_file.name, "(delete the file to measure again)")
else:
    prepare_data.run_images(root, max_seconds=MAX_SECONDS)

1,005,700 images, 0 already measured, 1,005,700 to do
  measured 2,000 of 1,005,700 in 2 s
  measured 4,000 of 1,005,700 in 4 s
  measured 6,000 of 1,005,700 in 5 s
  measured 8,000 of 1,005,700 in 7 s
  measured 10,000 of 1,005,700 in 8 s
  measured 12,000 of 1,005,700 in 9 s
  measured 14,000 of 1,005,700 in 11 s
  measured 16,000 of 1,005,700 in 12 s
  measured 18,000 of 1,005,700 in 14 s
  measured 20,000 of 1,005,700 in 15 s
  measured 22,000 of 1,005,700 in 17 s
  measured 24,000 of 1,005,700 in 19 s
  measured 26,000 of 1,005,700 in 20 s
  measured 28,000 of 1,005,700 in 22 s
  measured 30,000 of 1,005,700 in 23 s
  measured 32,000 of 1,005,700 in 25 s
  measured 34,000 of 1,005,700 in 26 s
  measured 36,000 of 1,005,700 in 28 s
  measured 38,000 of 1,005,700 in 29 s
  measured 40,000 of 1,005,700 in 30 s
  measured 42,000 of 1,005,700 in 32 s
  measured 44,000 of 1,005,700 in 33 s
  measured 46,000 of 1,005,700 in 34 s
  measured 48,000 of 1,005,700 in 35 s
  measured 50,000 of 1,005,700 in 37 s
  measured 52,000 of 1,005,700 in 39 s
  measured 54,000 of 1,005,700 in 40 s
  measured 56,000 of 1,005,700 in 42 s
  measured 58,000 of 1,005,700 in 43 s
  measured 60,000 of 1,005,700 in 45 s
  measured 62,000 of 1,005,700 in 46 s
  measured 64,000 of 1,005,700 in 48 s
  measured 66,000 of 1,005,700 in 49 s
  measured 68,000 of 1,005,700 in 51 s
  measured 70,000 of 1,005,700 in 53 s
  measured 72,000 of 1,005,700 in 54 s
  measured 74,000 of 1,005,700 in 56 s
  measured 76,000 of 1,005,700 in 58 s
  measured 78,000 of 1,005,700 in 59 s
  measured 80,000 of 1,005,700 in 61 s
  measured 82,000 of 1,005,700 in 63 s
  measured 84,000 of 1,005,700 in 64 s
  measured 86,000 of 1,005,700 in 65 s
  measured 88,000 of 1,005,700 in 67 s
  measured 90,000 of 1,005,700 in 69 s
  measured 92,000 of 1,005,700 in 70 s
  measured 94,000 of 1,005,700 in 72 s
  measured 96,000 of 1,005,700 in 73 s
  measured 98,000 of 1,005,700 in 75 s
  measured 100,000 of 1,005,700 in 77 s
  measured 102,000 of 1,005,700 in 78 s
  measured 104,000 of 1,005,700 in 80 s
  measured 106,000 of 1,005,700 in 82 s
  measured 108,000 of 1,005,700 in 83 s
  measured 110,000 of 1,005,700 in 85 s
  measured 112,000 of 1,005,700 in 87 s
  measured 114,000 of 1,005,700 in 88 s
  measured 116,000 of 1,005,700 in 90 s
  measured 118,000 of 1,005,700 in 92 s
  measured 120,000 of 1,005,700 in 93 s
  measured 122,000 of 1,005,700 in 95 s
  measured 124,000 of 1,005,700 in 96 s
  measured 126,000 of 1,005,700 in 98 s
  measured 128,000 of 1,005,700 in 99 s
  measured 130,000 of 1,005,700 in 101 s
  measured 132,000 of 1,005,700 in 102 s
  measured 134,000 of 1,005,700 in 104 s
  measured 136,000 of 1,005,700 in 105 s
  measured 138,000 of 1,005,700 in 107 s
  measured 140,000 of 1,005,700 in 109 s
  measured 142,000 of 1,005,700 in 110 s
  measured 144,000 of 1,005,700 in 112 s
  measured 146,000 of 1,005,700 in 114 s
  measured 148,000 of 1,005,700 in 115 s
  measured 150,000 of 1,005,700 in 117 s
  measured 152,000 of 1,005,700 in 118 s
  measured 154,000 of 1,005,700 in 120 s
  measured 156,000 of 1,005,700 in 121 s
  measured 158,000 of 1,005,700 in 123 s
  measured 160,000 of 1,005,700 in 124 s
  measured 162,000 of 1,005,700 in 126 s
  measured 164,000 of 1,005,700 in 127 s
  measured 166,000 of 1,005,700 in 129 s
  measured 168,000 of 1,005,700 in 130 s
  measured 170,000 of 1,005,700 in 132 s
  measured 172,000 of 1,005,700 in 133 s
  measured 174,000 of 1,005,700 in 135 s
  measured 176,000 of 1,005,700 in 137 s
  measured 178,000 of 1,005,700 in 138 s
  measured 180,000 of 1,005,700 in 140 s
  measured 182,000 of 1,005,700 in 141 s
  measured 184,000 of 1,005,700 in 143 s
  measured 186,000 of 1,005,700 in 144 s
  measured 188,000 of 1,005,700 in 146 s
  measured 190,000 of 1,005,700 in 147 s
  measured 192,000 of 1,005,700 in 149 s
  measured 194,000 of 1,005,700 in 151 s
  measured 196,000 of 1,005,700 in 152 s
  measured 198,000 of 1,005,700 in 154 s
  measured 200,000 of 1,005,700 in 155 s
  measured 202,000 of 1,005,700 in 157 s
  measured 204,000 of 1,005,700 in 159 s
  measured 206,000 of 1,005,700 in 160 s
  measured 208,000 of 1,005,700 in 162 s
  measured 210,000 of 1,005,700 in 163 s
  measured 212,000 of 1,005,700 in 165 s
  measured 214,000 of 1,005,700 in 167 s
  measured 216,000 of 1,005,700 in 168 s
  measured 218,000 of 1,005,700 in 170 s
  measured 220,000 of 1,005,700 in 171 s
  measured 222,000 of 1,005,700 in 173 s
  measured 224,000 of 1,005,700 in 175 s
  measured 226,000 of 1,005,700 in 176 s
  measured 228,000 of 1,005,700 in 178 s
  measured 230,000 of 1,005,700 in 179 s
  measured 232,000 of 1,005,700 in 180 s
  measured 234,000 of 1,005,700 in 182 s
  measured 236,000 of 1,005,700 in 184 s
  measured 238,000 of 1,005,700 in 185 s
  measured 240,000 of 1,005,700 in 187 s
  measured 242,000 of 1,005,700 in 188 s
  measured 244,000 of 1,005,700 in 190 s
  measured 246,000 of 1,005,700 in 191 s
  measured 248,000 of 1,005,700 in 193 s
  measured 250,000 of 1,005,700 in 194 s
  measured 252,000 of 1,005,700 in 195 s
  measured 254,000 of 1,005,700 in 197 s
  measured 256,000 of 1,005,700 in 198 s
  measured 258,000 of 1,005,700 in 200 s
  measured 260,000 of 1,005,700 in 201 s
  measured 262,000 of 1,005,700 in 203 s
  measured 264,000 of 1,005,700 in 205 s
  measured 266,000 of 1,005,700 in 206 s
  measured 268,000 of 1,005,700 in 207 s
  measured 270,000 of 1,005,700 in 209 s
  measured 272,000 of 1,005,700 in 210 s
  measured 274,000 of 1,005,700 in 212 s
  measured 276,000 of 1,005,700 in 213 s
  measured 278,000 of 1,005,700 in 215 s
  measured 280,000 of 1,005,700 in 216 s
  measured 282,000 of 1,005,700 in 217 s
  measured 284,000 of 1,005,700 in 219 s
  measured 286,000 of 1,005,700 in 220 s
  measured 288,000 of 1,005,700 in 222 s
  measured 290,000 of 1,005,700 in 223 s
  measured 292,000 of 1,005,700 in 225 s
  measured 294,000 of 1,005,700 in 226 s
  measured 296,000 of 1,005,700 in 228 s
  measured 298,000 of 1,005,700 in 229 s
  measured 300,000 of 1,005,700 in 231 s
  measured 302,000 of 1,005,700 in 232 s
  measured 304,000 of 1,005,700 in 234 s
  measured 306,000 of 1,005,700 in 235 s
  measured 308,000 of 1,005,700 in 237 s
  measured 310,000 of 1,005,700 in 239 s
  measured 312,000 of 1,005,700 in 240 s
  measured 314,000 of 1,005,700 in 242 s
  measured 316,000 of 1,005,700 in 243 s
  measured 318,000 of 1,005,700 in 245 s
  measured 320,000 of 1,005,700 in 246 s
  measured 322,000 of 1,005,700 in 248 s
  measured 324,000 of 1,005,700 in 249 s
  measured 326,000 of 1,005,700 in 251 s
  measured 328,000 of 1,005,700 in 252 s
  measured 330,000 of 1,005,700 in 254 s
  measured 332,000 of 1,005,700 in 256 s
  measured 334,000 of 1,005,700 in 257 s
  measured 336,000 of 1,005,700 in 259 s
  measured 338,000 of 1,005,700 in 261 s
  measured 340,000 of 1,005,700 in 263 s
  measured 342,000 of 1,005,700 in 264 s
  measured 344,000 of 1,005,700 in 266 s
  measured 346,000 of 1,005,700 in 267 s
  measured 348,000 of 1,005,700 in 269 s
  measured 350,000 of 1,005,700 in 270 s
  measured 352,000 of 1,005,700 in 272 s
  measured 354,000 of 1,005,700 in 273 s
  measured 356,000 of 1,005,700 in 275 s
  measured 358,000 of 1,005,700 in 277 s
  measured 360,000 of 1,005,700 in 278 s
  measured 362,000 of 1,005,700 in 280 s
  measured 364,000 of 1,005,700 in 281 s
  measured 366,000 of 1,005,700 in 283 s
  measured 368,000 of 1,005,700 in 284 s
  measured 370,000 of 1,005,700 in 286 s
  measured 372,000 of 1,005,700 in 288 s
  measured 374,000 of 1,005,700 in 289 s
  measured 376,000 of 1,005,700 in 291 s
  measured 378,000 of 1,005,700 in 292 s
  measured 380,000 of 1,005,700 in 294 s
  measured 382,000 of 1,005,700 in 295 s
  measured 384,000 of 1,005,700 in 297 s
  measured 386,000 of 1,005,700 in 298 s
  measured 388,000 of 1,005,700 in 300 s
  measured 390,000 of 1,005,700 in 301 s
  measured 392,000 of 1,005,700 in 303 s
  measured 394,000 of 1,005,700 in 304 s
  measured 396,000 of 1,005,700 in 306 s
  measured 398,000 of 1,005,700 in 307 s
  measured 400,000 of 1,005,700 in 309 s
  measured 402,000 of 1,005,700 in 310 s
  measured 404,000 of 1,005,700 in 311 s
  measured 406,000 of 1,005,700 in 313 s
  measured 408,000 of 1,005,700 in 315 s
  measured 410,000 of 1,005,700 in 316 s
  measured 412,000 of 1,005,700 in 318 s
  measured 414,000 of 1,005,700 in 320 s
  measured 416,000 of 1,005,700 in 321 s
  measured 418,000 of 1,005,700 in 323 s
  measured 420,000 of 1,005,700 in 324 s
  measured 422,000 of 1,005,700 in 326 s
  measured 424,000 of 1,005,700 in 328 s
  measured 426,000 of 1,005,700 in 329 s
  measured 428,000 of 1,005,700 in 331 s
  measured 430,000 of 1,005,700 in 332 s
  measured 432,000 of 1,005,700 in 334 s
  measured 434,000 of 1,005,700 in 336 s
  measured 436,000 of 1,005,700 in 337 s
  measured 438,000 of 1,005,700 in 339 s
  measured 440,000 of 1,005,700 in 340 s
  measured 442,000 of 1,005,700 in 342 s
  measured 444,000 of 1,005,700 in 344 s
  measured 446,000 of 1,005,700 in 346 s
  measured 448,000 of 1,005,700 in 347 s
  measured 450,000 of 1,005,700 in 349 s
  measured 452,000 of 1,005,700 in 350 s
  measured 454,000 of 1,005,700 in 352 s
  measured 456,000 of 1,005,700 in 353 s
  measured 458,000 of 1,005,700 in 355 s
  measured 460,000 of 1,005,700 in 356 s
  measured 462,000 of 1,005,700 in 358 s
  measured 464,000 of 1,005,700 in 359 s
  measured 466,000 of 1,005,700 in 361 s
  measured 468,000 of 1,005,700 in 363 s
  measured 470,000 of 1,005,700 in 364 s
  measured 472,000 of 1,005,700 in 366 s
  measured 474,000 of 1,005,700 in 367 s
  measured 476,000 of 1,005,700 in 369 s
  measured 478,000 of 1,005,700 in 370 s
  measured 480,000 of 1,005,700 in 372 s
  measured 482,000 of 1,005,700 in 373 s
  measured 484,000 of 1,005,700 in 375 s
  measured 486,000 of 1,005,700 in 376 s
  measured 488,000 of 1,005,700 in 378 s
  measured 490,000 of 1,005,700 in 379 s
  measured 492,000 of 1,005,700 in 381 s
  measured 494,000 of 1,005,700 in 382 s
  measured 496,000 of 1,005,700 in 384 s
  measured 498,000 of 1,005,700 in 385 s
  measured 500,000 of 1,005,700 in 387 s
  measured 502,000 of 1,005,700 in 388 s
  measured 504,000 of 1,005,700 in 390 s
  measured 506,000 of 1,005,700 in 391 s
  measured 508,000 of 1,005,700 in 393 s
  measured 510,000 of 1,005,700 in 394 s
  measured 512,000 of 1,005,700 in 396 s
  measured 514,000 of 1,005,700 in 397 s
  measured 516,000 of 1,005,700 in 399 s
  measured 518,000 of 1,005,700 in 401 s
  measured 520,000 of 1,005,700 in 402 s
  measured 522,000 of 1,005,700 in 404 s
  measured 524,000 of 1,005,700 in 405 s
  measured 526,000 of 1,005,700 in 407 s
  measured 528,000 of 1,005,700 in 408 s
  measured 530,000 of 1,005,700 in 410 s
  measured 532,000 of 1,005,700 in 411 s
  measured 534,000 of 1,005,700 in 413 s
  measured 536,000 of 1,005,700 in 415 s
  measured 538,000 of 1,005,700 in 416 s
  measured 540,000 of 1,005,700 in 417 s
  measured 542,000 of 1,005,700 in 419 s
  measured 544,000 of 1,005,700 in 420 s
  measured 546,000 of 1,005,700 in 422 s
  measured 548,000 of 1,005,700 in 423 s
  measured 550,000 of 1,005,700 in 425 s
  measured 552,000 of 1,005,700 in 427 s
  measured 554,000 of 1,005,700 in 428 s
  measured 556,000 of 1,005,700 in 430 s
  measured 558,000 of 1,005,700 in 431 s
  measured 560,000 of 1,005,700 in 433 s
  measured 562,000 of 1,005,700 in 434 s
  measured 564,000 of 1,005,700 in 436 s
  measured 566,000 of 1,005,700 in 437 s
  measured 568,000 of 1,005,700 in 439 s
  measured 570,000 of 1,005,700 in 440 s
  measured 572,000 of 1,005,700 in 442 s
  measured 574,000 of 1,005,700 in 444 s
  measured 576,000 of 1,005,700 in 446 s
  measured 578,000 of 1,005,700 in 447 s
  measured 580,000 of 1,005,700 in 449 s
  measured 582,000 of 1,005,700 in 450 s
  measured 584,000 of 1,005,700 in 452 s
  measured 586,000 of 1,005,700 in 453 s
  measured 588,000 of 1,005,700 in 455 s
  measured 590,000 of 1,005,700 in 456 s
  measured 592,000 of 1,005,700 in 458 s
  measured 594,000 of 1,005,700 in 459 s
  measured 596,000 of 1,005,700 in 461 s
  measured 598,000 of 1,005,700 in 462 s
  measured 600,000 of 1,005,700 in 464 s
  measured 602,000 of 1,005,700 in 465 s
  measured 604,000 of 1,005,700 in 467 s
  measured 606,000 of 1,005,700 in 468 s
  measured 608,000 of 1,005,700 in 470 s
  measured 610,000 of 1,005,700 in 471 s
  measured 612,000 of 1,005,700 in 473 s
  measured 614,000 of 1,005,700 in 474 s
  measured 616,000 of 1,005,700 in 476 s
  measured 618,000 of 1,005,700 in 477 s
  measured 620,000 of 1,005,700 in 479 s
  measured 622,000 of 1,005,700 in 480 s
  measured 624,000 of 1,005,700 in 481 s
  measured 626,000 of 1,005,700 in 483 s
  measured 628,000 of 1,005,700 in 484 s
  measured 630,000 of 1,005,700 in 486 s
  measured 632,000 of 1,005,700 in 487 s
  measured 634,000 of 1,005,700 in 489 s
  measured 636,000 of 1,005,700 in 490 s
  measured 638,000 of 1,005,700 in 491 s
  measured 640,000 of 1,005,700 in 493 s
  measured 642,000 of 1,005,700 in 494 s
  measured 644,000 of 1,005,700 in 495 s
  measured 646,000 of 1,005,700 in 497 s
  measured 648,000 of 1,005,700 in 498 s
  measured 650,000 of 1,005,700 in 499 s
  measured 652,000 of 1,005,700 in 501 s
  measured 654,000 of 1,005,700 in 502 s
  measured 656,000 of 1,005,700 in 504 s
  measured 658,000 of 1,005,700 in 506 s
  measured 660,000 of 1,005,700 in 507 s
  measured 662,000 of 1,005,700 in 509 s
  measured 664,000 of 1,005,700 in 510 s
  measured 666,000 of 1,005,700 in 512 s
  measured 668,000 of 1,005,700 in 513 s
  measured 670,000 of 1,005,700 in 515 s
  measured 672,000 of 1,005,700 in 517 s
  measured 674,000 of 1,005,700 in 518 s
  measured 676,000 of 1,005,700 in 520 s
  measured 678,000 of 1,005,700 in 521 s
  measured 680,000 of 1,005,700 in 522 s
  measured 682,000 of 1,005,700 in 524 s
  measured 684,000 of 1,005,700 in 525 s
  measured 686,000 of 1,005,700 in 527 s
  measured 688,000 of 1,005,700 in 528 s
  measured 690,000 of 1,005,700 in 530 s
  measured 692,000 of 1,005,700 in 531 s
  measured 694,000 of 1,005,700 in 533 s
  measured 696,000 of 1,005,700 in 534 s
  measured 698,000 of 1,005,700 in 536 s
  measured 700,000 of 1,005,700 in 537 s
  measured 702,000 of 1,005,700 in 539 s
  measured 704,000 of 1,005,700 in 541 s
  measured 706,000 of 1,005,700 in 542 s
  measured 708,000 of 1,005,700 in 543 s
  measured 710,000 of 1,005,700 in 545 s
  measured 712,000 of 1,005,700 in 546 s
  measured 714,000 of 1,005,700 in 548 s
  measured 716,000 of 1,005,700 in 549 s
  measured 718,000 of 1,005,700 in 551 s
  measured 720,000 of 1,005,700 in 552 s
  measured 722,000 of 1,005,700 in 554 s
  measured 724,000 of 1,005,700 in 555 s
  measured 726,000 of 1,005,700 in 557 s
  measured 728,000 of 1,005,700 in 558 s
  measured 730,000 of 1,005,700 in 560 s
  measured 732,000 of 1,005,700 in 561 s
  measured 734,000 of 1,005,700 in 563 s
  measured 736,000 of 1,005,700 in 564 s
  measured 738,000 of 1,005,700 in 566 s
  measured 740,000 of 1,005,700 in 567 s
  measured 742,000 of 1,005,700 in 569 s
  measured 744,000 of 1,005,700 in 570 s
  measured 746,000 of 1,005,700 in 572 s
  measured 748,000 of 1,005,700 in 574 s
  measured 750,000 of 1,005,700 in 575 s
  measured 752,000 of 1,005,700 in 577 s
  measured 754,000 of 1,005,700 in 578 s
  measured 756,000 of 1,005,700 in 580 s
  measured 758,000 of 1,005,700 in 581 s
  measured 760,000 of 1,005,700 in 582 s
  measured 762,000 of 1,005,700 in 584 s
  measured 764,000 of 1,005,700 in 585 s
  measured 766,000 of 1,005,700 in 587 s
  measured 768,000 of 1,005,700 in 588 s
  measured 770,000 of 1,005,700 in 590 s
  measured 772,000 of 1,005,700 in 592 s
  measured 774,000 of 1,005,700 in 593 s
  measured 776,000 of 1,005,700 in 595 s
  measured 778,000 of 1,005,700 in 596 s
  measured 780,000 of 1,005,700 in 598 s
  measured 782,000 of 1,005,700 in 600 s
  measured 784,000 of 1,005,700 in 601 s
  measured 786,000 of 1,005,700 in 603 s
  measured 788,000 of 1,005,700 in 604 s
  measured 790,000 of 1,005,700 in 606 s
  measured 792,000 of 1,005,700 in 607 s
  measured 794,000 of 1,005,700 in 609 s
  measured 796,000 of 1,005,700 in 611 s
  measured 798,000 of 1,005,700 in 612 s
  measured 800,000 of 1,005,700 in 614 s
  measured 802,000 of 1,005,700 in 616 s
  measured 804,000 of 1,005,700 in 618 s
  measured 806,000 of 1,005,700 in 620 s
  measured 808,000 of 1,005,700 in 621 s
  measured 810,000 of 1,005,700 in 623 s
  measured 812,000 of 1,005,700 in 625 s
  measured 814,000 of 1,005,700 in 627 s
  measured 816,000 of 1,005,700 in 629 s
  measured 818,000 of 1,005,700 in 631 s
  measured 820,000 of 1,005,700 in 632 s
  measured 822,000 of 1,005,700 in 634 s
  measured 824,000 of 1,005,700 in 636 s
  measured 826,000 of 1,005,700 in 638 s
  measured 828,000 of 1,005,700 in 639 s
  measured 830,000 of 1,005,700 in 641 s
  measured 832,000 of 1,005,700 in 643 s
  measured 834,000 of 1,005,700 in 645 s
  measured 836,000 of 1,005,700 in 647 s
  measured 838,000 of 1,005,700 in 649 s
  measured 840,000 of 1,005,700 in 650 s
  measured 842,000 of 1,005,700 in 652 s
  measured 844,000 of 1,005,700 in 654 s
  measured 846,000 of 1,005,700 in 656 s
  measured 848,000 of 1,005,700 in 657 s
  measured 850,000 of 1,005,700 in 659 s
  measured 852,000 of 1,005,700 in 661 s
  measured 854,000 of 1,005,700 in 662 s
  measured 856,000 of 1,005,700 in 664 s
  measured 858,000 of 1,005,700 in 666 s
  measured 860,000 of 1,005,700 in 667 s
  measured 862,000 of 1,005,700 in 669 s
  measured 864,000 of 1,005,700 in 671 s
  measured 866,000 of 1,005,700 in 673 s
  measured 868,000 of 1,005,700 in 674 s
  measured 870,000 of 1,005,700 in 676 s
  measured 872,000 of 1,005,700 in 678 s
  measured 874,000 of 1,005,700 in 680 s
  measured 876,000 of 1,005,700 in 681 s
  measured 878,000 of 1,005,700 in 683 s
  measured 880,000 of 1,005,700 in 685 s
  measured 882,000 of 1,005,700 in 686 s
  measured 884,000 of 1,005,700 in 688 s
  measured 886,000 of 1,005,700 in 690 s
  measured 888,000 of 1,005,700 in 691 s
  measured 890,000 of 1,005,700 in 693 s
  measured 892,000 of 1,005,700 in 695 s
  measured 894,000 of 1,005,700 in 696 s
  measured 896,000 of 1,005,700 in 698 s
  measured 898,000 of 1,005,700 in 699 s
  measured 900,000 of 1,005,700 in 701 s
  measured 902,000 of 1,005,700 in 702 s
  measured 904,000 of 1,005,700 in 704 s
  measured 906,000 of 1,005,700 in 705 s
  measured 908,000 of 1,005,700 in 707 s
  measured 910,000 of 1,005,700 in 709 s
  measured 912,000 of 1,005,700 in 710 s
  measured 914,000 of 1,005,700 in 712 s
  measured 916,000 of 1,005,700 in 714 s
  measured 918,000 of 1,005,700 in 715 s
  measured 920,000 of 1,005,700 in 717 s
  measured 922,000 of 1,005,700 in 719 s
  measured 924,000 of 1,005,700 in 720 s
  measured 926,000 of 1,005,700 in 722 s
  measured 928,000 of 1,005,700 in 724 s
  measured 930,000 of 1,005,700 in 726 s
  measured 932,000 of 1,005,700 in 727 s
  measured 934,000 of 1,005,700 in 729 s
  measured 936,000 of 1,005,700 in 730 s
  measured 938,000 of 1,005,700 in 732 s
  measured 940,000 of 1,005,700 in 733 s
  measured 942,000 of 1,005,700 in 734 s
  measured 944,000 of 1,005,700 in 736 s
  measured 946,000 of 1,005,700 in 737 s
  measured 948,000 of 1,005,700 in 739 s
  measured 950,000 of 1,005,700 in 740 s
  measured 952,000 of 1,005,700 in 742 s
  measured 954,000 of 1,005,700 in 743 s
  measured 956,000 of 1,005,700 in 745 s
  measured 958,000 of 1,005,700 in 746 s
  measured 960,000 of 1,005,700 in 748 s
  measured 962,000 of 1,005,700 in 749 s
  measured 964,000 of 1,005,700 in 751 s
  measured 966,000 of 1,005,700 in 752 s
  measured 968,000 of 1,005,700 in 754 s
  measured 970,000 of 1,005,700 in 755 s
  measured 972,000 of 1,005,700 in 757 s
  measured 974,000 of 1,005,700 in 758 s
  measured 976,000 of 1,005,700 in 760 s
  measured 978,000 of 1,005,700 in 761 s

In [8]:
# Summary of the image measurements per class
cols = ["side", "modules", "border", "dark_frac"]
feat = pd.read_csv(features_file, keep_default_na=False, na_values={c: [""] for c in cols})
bad = feat["error"].fillna("").ne("")
print(f"{len(feat):,} images measured, {int(bad.sum()):,} could not be measured")
ok = feat[~bad]
pd.DataFrame({
    "images": ok.groupby("cls").size(),
    "Micro QR share (under 21 modules)": ok.groupby("cls")["modules"].apply(lambda s: (s < 21).mean()).round(4),
    "median modules per side": ok.groupby("cls")["modules"].median(),
    "largest modules per side": ok.groupby("cls")["modules"].max(),
    "median dark fraction": ok.groupby("cls")["dark_frac"].median().round(4),
}).T

1,005,700 images measured, 0 could not be measured

cls                                     benign    malicious
images                             429957.0000  575743.0000
Micro QR share (under 21 modules)       0.0243       0.0675
median modules per side                29.0000      29.0000
largest modules per side              117.0000     161.0000
median dark fraction                    0.3156       0.3097

## 4. Build the items table

One row per kept QR code. The table joins the manifest (URL, label and URL features), the split, the canvas fit and the image measurements, and saves them to `items.csv.gz`.

**The split rule** was decided in `1_eda.ipynb` section 6 and is applied here without change:

- Benign and malicious rows are each split 70/15/15 into train, validation and test (70% for training, 15% for tuning, 15% for the final test).
- The split is grouped by domain (the site name, for example `wikipedia.org`), so all rows of one domain stay in one split. This stops a model from scoring well just because it saw other pages of the same site during training.
- The largest domains fill train first, and the remaining domains are shuffled and dealt to validation and test, with seed 0.

`prepare_data.run_items` also checks that every domain sits in one split, that item ids run from 0 to n-1, and that labels match the class folder.

In [9]:
# Build and save the items table and its summary
prepare_data.run_items(root)

saved c:\Users\joetn\convolutional_vae_quishing\data\processed\items.csv.gz: 1,005,700 items, data version 0781657d11c5, image features filled for 1,005,700 items
saved c:\Users\joetn\convolutional_vae_quishing\data\processed\items_summary.json

In [10]:
# Read the saved table back the way the model notebooks do, and look at the first rows
items = prepare_data.load_items(PROC_DIR)
print(items.shape)
items.head()

(1005700, 26)

,item_id,cls,label,index,file,url,split,domain,host,fits_canvas,...,is_https,host_is_ip,n_host_labels,path_len,digit_ratio,side,modules,border,dark_frac,qr_version
0,0,benign,0,1,benign_000001.png,http://freshrpms.net/,train,freshrpms.net,freshrpms.net,True,...,False,False,2,1,0.000000,198,25,4.0,0.303030,2.0
1,1,benign,0,2,benign_000002.png,http://lists.freshrpms.net/mailman/listinfo/rp...,train,freshrpms.net,lists.freshrpms.net,True,...,False,False,3,26,0.000000,222,29,4.0,0.316289,3.0
2,2,benign,0,3,benign_000003.png,http://www.boquist.net/stort-sup-brev,validation,boquist.net,www.boquist.net,True,...,False,False,3,15,0.000000,222,29,4.0,0.314098,3.0
3,3,benign,0,6,benign_000006.png,http://hesketh.com,test,hesketh.com,hesketh.com,True,...,False,False,2,0,0.000000,198,25,4.0,0.304867,2.0
4,4,benign,0,7,benign_000007.png,http://seeker.dice.com/seeker.epl?rel_code=31,validation,dice.com,seeker.dice.com,True,...,False,False,3,11,0.044444,222,29,4.0,0.315559,3.0

## 5. Checks on the splits

Two checks that must hold: no domain appears in more than one split, and no validation or test row shares a host with a train row of its own class. Then the counts per split.

In [11]:
# Checks (each domain sits in one split, no host is shared with train)
checks = {}
for cls, g in items.groupby("cls"):
    train_hosts = set(g.loc[g["split"] == "train", "host"])
    checks[cls] = {
        "domains found in more than one split": int((g.groupby("domain")["split"].nunique() > 1).sum()),
        "validation or test rows sharing a host with train": int(g.loc[g["split"] != "train", "host"].isin(train_hosts).sum()),
    }
display(pd.DataFrame(checks))
assert all(v == 0 for c in checks.values() for v in c.values())

                                                   benign  malicious
domains found in more than one split                    0          0
validation or test rows sharing a host with train       0          0

In [12]:
# Class counts per split, the malicious share of each split, and how large the biggest domain is
counts = items.pivot_table(index="split", columns="cls", values="file", aggfunc="count").loc[SPLIT_NAMES]
counts["malicious share of split"] = counts["malicious"] / (counts["benign"] + counts["malicious"])
counts["benign share of class"] = counts["benign"] / counts["benign"].sum()
counts["malicious share of class"] = counts["malicious"] / counts["malicious"].sum()
counts["largest domain, share of split rows"] = pd.Series({s: g["domain"].value_counts(normalize=True).iloc[0] for s, g in items.groupby("split")})
counts.round(4)

cls,benign,malicious,malicious share of split,benign share of class,malicious share of class,"largest domain, share of split rows"
split,,,,,,
train,300969,403020,0.5725,0.70,0.70,0.021
validation,64494,86361,0.5725,0.15,0.15,0.000
test,64494,86362,0.5725,0.15,0.15,0.000

**Reading.** Each class lands close to 70/15/15, and every split is about 57% malicious, so the AUPRC of a random scorer is about 0.57 in all three. No domain is split across train, validation and test, and no validation or test row shares a host with a training row of its own class. The largest domain (about 2% of the train rows) sits in train, and the largest domain in validation or test is a negligible share, as intended.

Two things to know about the grouping:

- A host that is an IP address has no registered domain, so the `domain` column holds the last two numbers of the address (for example `115.240`). Rows of the same IP always stay together, and unrelated IPs that share those two numbers move together too.
- The classes are split separately, so a domain that appears in both classes can land in different splits. The next cell counts how often this affects malicious validation and test rows.

In [13]:
# Malicious validation and test rows whose domain also appears in the benign train split
benign_train_domains = set(items.loc[(items["cls"] == "benign") & (items["split"] == "train"), "domain"])
mal_eval = items[(items["cls"] == "malicious") & (items["split"] != "train")]
shared = mal_eval["domain"].isin(benign_train_domains)
print(f"{shared.sum():,} of {len(mal_eval):,} malicious validation and test rows ({shared.mean():.3%}) share a domain with a benign train row")

99 of 172,723 malicious validation and test rows (0.057%) share a domain with a benign train row

## 6. Codes outside the canvas, per split

The image models use only the rows with `fits_canvas` true, and the excluded codes are reported per split. URL models use every row.

In [14]:
# Codes outside the 65 x 65 canvas, per split and class
excluded_split = items.groupby(["split", "cls"])["fits_canvas"].agg(rows="size", outside_canvas=lambda s: int((~s).sum()))
excluded_split["outside share"] = excluded_split["outside_canvas"] / excluded_split["rows"]
excluded_split.loc[SPLIT_NAMES].round(4)

                        rows  outside_canvas  outside share
split      cls
train      benign     300969             106         0.0004
           malicious  403020            4271         0.0106
validation benign      64494              23         0.0004
           malicious   86361             113         0.0013
test       benign      64494              28         0.0004
           malicious   86362             122         0.0014

## 7. What uses which rows

| Model | Fitted on | Tuned on | Threshold set on | Scored on |
| --- | --- | --- | --- | --- |
| Floors and the VAE | benign train rows | validation rows | benign validation rows | validation and test rows |
| Supervised reference | benign and malicious train rows | validation rows | benign validation rows | validation and test rows |

The test rows are used once per model, after the configuration is fixed on validation. Malicious train rows are used only by the supervised reference.

The model notebooks read the items table with `load_items` and take these rows from it. The image models pass `fits_canvas_only=True`, and the URL models use every row.

### Files this notebook saved in `data/processed/`

| File | What it holds |
| --- | --- |
| `image_grid_sizes.csv.gz` | grid size and canvas fit of every kept image |
| `canvas_exclusion_summary.json` | counts of excluded codes per class |
| `image_features.csv.gz` | modules, quiet zone and dark fraction of every kept image |
| `items.csv.gz` | the items table read by the model notebooks |
| `items_summary.json` | counts per split, excluded and truncated codes, and a short `data_version` that changes if the rows or splits change |